/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\\Program Files\\Java\\jdk-16.0.2\\include\\jni.h>
/* Header for class fileSearch */

#ifndef _Included_fileSearch
#define _Included_fileSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fileSearch
 * Method:    getDuplicateFiles
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_fileSearch_getDuplicateFiles
  (JNIEnv *, jclass, jstring);

/*
 * Class:     fileSearch
 * Method:    getDuplicateDir
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_fileSearch_getDuplicateDir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
